# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doubanFM_revision.ui'
#
# Created: Wed May 29 22:26:19 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(250, 550)
        Form.setMinimumSize(QtCore.QSize(250, 550))
        Form.setMaximumSize(QtCore.QSize(250, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("image/logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        Form.setObjectName(_fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 12, 226, 52))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.opLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.opLayout.setSpacing(7)
        self.opLayout.setMargin(0)
        self.opLayout.setObjectName(_fromUtf8("opLayout"))
        self.stopButton = HexLabel(self.layoutWidget)
        self.stopButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopButton.setPixmap(QtGui.QPixmap(_fromUtf8("image/Selection_005.png")))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.opLayout.addWidget(self.stopButton)
        self.nextButton = HexLabel(self.layoutWidget)
        self.nextButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton.setTextFormat(QtCore.Qt.AutoText)
        self.nextButton.setPixmap(QtGui.QPixmap(_fromUtf8("image/Selection_004.png")))
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.opLayout.addWidget(self.nextButton)
        self.likeButton = HexLabel(self.layoutWidget)
        self.likeButton.setEnabled(False)
        self.likeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.likeButton.setTextFormat(QtCore.Qt.AutoText)
        self.likeButton.setPixmap(QtGui.QPixmap(_fromUtf8("image/grepheart.png")))
        self.likeButton.setObjectName(_fromUtf8("likeButton"))
        self.opLayout.addWidget(self.likeButton)
        self.notlikeButton = HexLabel(self.layoutWidget)
        self.notlikeButton.setEnabled(False)
        self.notlikeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notlikeButton.setTextFormat(QtCore.Qt.AutoText)
        self.notlikeButton.setPixmap(QtGui.QPixmap(_fromUtf8("image/Selection_003.png")))
        self.notlikeButton.setObjectName(_fromUtf8("notlikeButton"))
        self.opLayout.addWidget(self.notlikeButton)
        self.opLayout.setStretch(0, 10)
        self.tline = QtGui.QFrame(Form)
        self.tline.setGeometry(QtCore.QRect(0, 468, 250, 16))
        self.tline.setFrameShape(QtGui.QFrame.HLine)
        self.tline.setFrameShadow(QtGui.QFrame.Sunken)
        self.tline.setObjectName(_fromUtf8("tline"))
        self.cover = QtGui.QLabel(Form)
        self.cover.setGeometry(QtCore.QRect(0, 110, 250, 250))
        self.cover.setText(_fromUtf8(""))
        self.cover.setPixmap(QtGui.QPixmap(_fromUtf8("image/cover.jpg")))
        self.cover.setScaledContents(True)
        self.cover.setObjectName(_fromUtf8("cover"))
        self.title = QtGui.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(10, 370, 150, 30))
        self.title.setMinimumSize(QtCore.QSize(250, 30))
        self.title.setText(_fromUtf8(""))
        self.title.setObjectName(_fromUtf8("title"))
        self.artist = QtGui.QLabel(Form)
        self.artist.setGeometry(QtCore.QRect(10, 410, 150, 20))
        self.artist.setMinimumSize(QtCore.QSize(250, 10))
        self.artist.setText(_fromUtf8(""))
        self.artist.setObjectName(_fromUtf8("artist"))
        self.channel = HexLabel(Form)
        self.channel.setGeometry(QtCore.QRect(10, 478, 240, 30))
        self.channel.setMinimumSize(QtCore.QSize(50, 30))
        self.channel.setObjectName(_fromUtf8("channel"))
        self.choice = QtGui.QLabel(self.channel)
        self.choice.setGeometry(QtCore.QRect(220, 5, 10, 20))
        self.choice.setText(_fromUtf8(""))
        self.choice.setPixmap(QtGui.QPixmap(_fromUtf8("image/play.png")))
        self.choice.setObjectName(_fromUtf8("choice"))
        self.bline = QtGui.QFrame(Form)
        self.bline.setGeometry(QtCore.QRect(0, 503, 250, 16))
        self.bline.setFrameShape(QtGui.QFrame.HLine)
        self.bline.setFrameShadow(QtGui.QFrame.Sunken)
        self.bline.setObjectName(_fromUtf8("bline"))
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 70, 254, 31))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.volumnLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.volumnLayout.setMargin(0)
        self.volumnLayout.setObjectName(_fromUtf8("volumnLayout"))
        self.volumn = HexLabel(self.layoutWidget1)
        self.volumn.setMinimumSize(QtCore.QSize(20, 0))
        self.volumn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.volumn.setPixmap(QtGui.QPixmap(_fromUtf8("image/volumnbutton.png")))
        self.volumn.setObjectName(_fromUtf8("volumn"))
        self.volumnLayout.addWidget(self.volumn)
        self.volumnSlider = QtGui.QSlider(self.layoutWidget1)
        self.volumnSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.volumnSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.volumnSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumnSlider.setObjectName(_fromUtf8("volumnSlider"))
        self.volumnSlider.setFixedWidth(150)
        self.volumnLayout.addWidget(self.volumnSlider)
        self.tpos = QtGui.QLabel(self.layoutWidget1)
        self.tpos.setMinimumSize(QtCore.QSize(70, 0))
        self.tpos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tpos.setObjectName(_fromUtf8("tpos"))
        self.volumnLayout.addWidget(self.tpos)
        self.userLabel = HexLabel(Form)
        self.userLabel.setGeometry(QtCore.QRect(10, 520, 20, 20))
        self.userLabel.setMinimumSize(QtCore.QSize(20, 0))
        self.userLabel.setPixmap(QtGui.QPixmap(_fromUtf8("image/user.png")))
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.username = QtGui.QLabel(Form)
        self.username.setGeometry(QtCore.QRect(38, 522, 70, 17))
        self.username.setMinimumSize(QtCore.QSize(70, 0))
        self.username.setObjectName(_fromUtf8("username"))
        self.quitLabel = HexLabel(Form)
        self.quitLabel.setGeometry(QtCore.QRect(220, 520, 20, 20))
        self.quitLabel.setPixmap(QtGui.QPixmap(_fromUtf8("image/x_alt.png")))
        self.quitLabel.setObjectName(_fromUtf8("quitLabel"))
        self.setting = HexLabel(Form)
        self.setting.setGeometry(QtCore.QRect(192, 520, 20, 20))
        self.setting.setPixmap(QtGui.QPixmap(_fromUtf8("image/wrench.png")))
        self.setting.setObjectName(_fromUtf8("setting"))
        self.redLabel = HexLabel(Form)
        self.redLabel.setGeometry(QtCore.QRect(102, 520, 25, 20))
        self.redLabel.setPixmap(QtGui.QPixmap(_fromUtf8("image/grep.png")))
        self.redLabel.setObjectName(_fromUtf8("redLabel"))
        self.rednum = QtGui.QLabel(Form)
        self.rednum.setGeometry(QtCore.QRect(127, 520, 50, 20))
        self.rednum.setMinimumSize(QtCore.QSize(50, 0))
        self.rednum.setObjectName(_fromUtf8("rednum"))
        
        self.current_channel = QtGui.QLabel(Form)
        self.current_channel.setGeometry(QtCore.QRect(10, 442, 240, 30))
        self.current_channel.setMinimumSize(QtCore.QSize(50, 30))
        self.current_channel.setObjectName(_fromUtf8("current_channel"))
        self.current_channel.setStyleSheet("font-size:10pt")
        self.choice_2 = QtGui.QLabel(self.current_channel)
        self.choice_2.setGeometry(QtCore.QRect(220, 5, 10, 20))
        self.choice_2.setText(_fromUtf8(""))
        self.choice_2.setPixmap(QtGui.QPixmap(_fromUtf8("image/ic_play_current1a.gif")))
        self.choice_2.setObjectName(_fromUtf8("choice_2"))

        #Popup menu
        self.menu = QtGui.QMenu(Form)
        self.redheartChannel = QtGui.QAction(_fromUtf8("红心兆赫"),self)
        self.redheartChannel.setEnabled(False)
        self.privateChannel = QtGui.QAction(_fromUtf8("私人兆赫"),self)
        self.privateChannel.setEnabled(False)
        self.collectChannel = QtGui.QMenu("收藏兆赫")
        self.collectChannel.setEnabled(False)
        self.moreChannel = QtGui.QMenu("公共兆赫")
        self.chineseChannel = QtGui.QAction("华语MHz",self)
        self.westernChannel = QtGui.QAction("欧美MHz",self)
        self.seventyChannel = QtGui.QAction("70MHz",self)
        self.eightyChannel = QtGui.QAction("80MHz",self)
        self.nintyChannel = QtGui.QAction("90MHz",self)
        self.cantoneseChannel = QtGui.QAction("粤语MHz",self)
        self.rockChannel = QtGui.QAction("摇滚MHz",self)
        self.folkChannel = QtGui.QAction("民谣MHz",self)
        self.lightmusicChannnel = QtGui.QAction("轻音乐MHz",self)
        self.movieChannel = QtGui.QAction("电影原声MHz",self)
        self.jazzChannel = QtGui.QAction("爵士MHz",self)
        self.elecChannel = QtGui.QAction("电子MHz",self)
        self.rapChannel = QtGui.QAction("说唱MHz",self)
        self.rnbChannel = QtGui.QAction("R&BMHz",self)
        self.japanChannel = QtGui.QAction("日语MHz",self)
        self.koreanChannel = QtGui.QAction("韩语MHz",self)
        self.womenChannel = QtGui.QAction("女声MHz",self)
        self.franceChannel = QtGui.QAction("法语MHz",self)
        self.moreChannel.addAction(self.chineseChannel)
        self.moreChannel.addAction(self.westernChannel)
        self.moreChannel.addAction(self.seventyChannel)
        self.moreChannel.addAction(self.eightyChannel)
        self.moreChannel.addAction(self.nintyChannel)
        self.moreChannel.addAction(self.cantoneseChannel)
        self.moreChannel.addAction(self.rockChannel)
        self.moreChannel.addAction(self.folkChannel)
        self.moreChannel.addAction(self.lightmusicChannnel)
        self.moreChannel.addAction(self.movieChannel)
        self.moreChannel.addAction(self.jazzChannel)
        self.moreChannel.addAction(self.elecChannel)
        self.moreChannel.addAction(self.rapChannel)
        self.moreChannel.addAction(self.rnbChannel)
        self.moreChannel.addAction(self.japanChannel)
        self.moreChannel.addAction(self.koreanChannel)
        self.moreChannel.addAction(self.womenChannel)
        self.moreChannel.addAction(self.franceChannel)
        self.menu.addMenu(self.moreChannel)
        self.menu.addAction(self.redheartChannel)
        self.menu.addAction(self.privateChannel)
        self.menu.addMenu(self.collectChannel)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Groove", None, QtGui.QApplication.UnicodeUTF8))
        self.channel.setText(QtGui.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">兆赫选择</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tpos.setText(QtGui.QApplication.translate("Form", "     ", None, QtGui.QApplication.UnicodeUTF8))
        self.username.setText(QtGui.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">未登录</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rednum.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))

class HexLabel(QtGui.QLabel):
    def __init__(self,parent=None):
        super(HexLabel,self).__init__(parent)
        self.checked = False;
        
    clicked = QtCore.pyqtSignal()
    toggled = QtCore.pyqtSignal(bool)
    mousemove = QtCore.pyqtSignal(QtGui.QMouseEvent)
    
    def mousePressEvent(self,event):
        if event.button() == QtCore.Qt.LeftButton:
            self.clicked.emit()
            self.checked = not self.checked
            self.toggled.emit(self.checked)
    def mouseMoveEvent(self,event):
        self.mousemove.emit(event)